language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"

notifications:
  email:
    recipients:
      - dudekzwp@gmail.com
      - patrykdudka9@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
